### ISSUE TITLE
Adjustable custom age group parameters

### ISSUE THREAD

**Issue by paugre** [semohr/risikogebiete_deutschland#24] opened 2021-11-07 11:57 UTC
Thank you for this handy map. 

It would be great to have the option to filter shown incidence rates by custom age ranges, such as for example 6-12 years to capture largely unvaccinated school age populations. 

It would be great to have the option to define custom age groups.

**Comment by semohr** [comment] 2021-11-07 15:32
Please have a look into closed issues before you open a new one
Duplicate of #5 

There is no way to implement the requested feature!

**Comment by semohr** [comment] 2021-11-07 15:33
Also duplicate of #15

**Closed by semohr** 2021-11-07 15:32 UTC
Labels: duplicate
