### ISSUE TITLE
Thank you - but a request of change

### ISSUE THREAD

**Issue by felitha** [semohr/risikogebiete_deutschland#15] opened 2021-08-24 21:00 UTC
Hi there,
can please split up the group 15-34 in two or three groups?
Maybe a splitting between schoolages will be helpful. 
05-10 11-15 16-20 21-29 30-..
So we have a bit more of a look into the kids... this will be very helpful these days. 
Thank you very much for your awesome work! 
All the best

**Comment by semohr** [comment] 2021-08-24 22:13
I agree that this would be interesting, but unfortunately, to my knowledge, this is not possible.
- The website is only visualizing RKI data, which does not have better age resolution
- There is the risklayer data, which has better resolution, but is only updated once a week, so I decided against it
I am not sure if there is a better data source by now, but I doubt it.

Best, Sebastian

Duplicate of #5.

**Closed** 2022-01-09 20:07 UTC
